# Generated by Django 5.0.3 on 2024-05-03 13:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('scm', '0007_product_discount_availability_product_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellcart',
            name='invoice',
        ),
        migrations.AddField(
            model_name='order',
            name='company_allowance',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Confirmed', 'Confirmed'), ('Partially-paid', 'Partially Paid'), ('Payment-completed', 'Payment Completed'), ('Cancelled', 'Cancelled')], default='Placed', max_length=32),
        ),
        migrations.AddField(
            model_name='sellcart',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='scm.ingredient'),
        ),
        migrations.AddField(
            model_name='sellcart',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_carts', to='sales.order'),
        ),
        migrations.AddField(
            model_name='sellcart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sellcart',
            name='total_price_with_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sellcart',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_carts', to=settings.AUTH_USER_MODEL),
        ),
    ]
