# Generated by Django 5.0.3 on 2024-05-07 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_sellcart_invoice_order_company_allowance_and_more'),
        ('scm', '0008_alter_product_name_alter_product_tax_percent_and_more'),
        ('users', '0010_user_deleted_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altercart',
            name='current_cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vat_percent',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='user_cart',
        ),
        migrations.AddField(
            model_name='altercart',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alter_carts', to='scm.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='altercart',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='is_full_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='orders',
            field=models.ManyToManyField(blank=True, to='sales.order'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='user_carts',
            field=models.ManyToManyField(blank=True, to='sales.usercart'),
        ),
        migrations.AddField(
            model_name='sellcart',
            name='cancelled_by',
            field=models.ManyToManyField(blank=True, related_name='cancelled_carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('updated', 'Updated'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Partially-paid', 'Partially Paid'), ('Payment-pending', 'Payment Pending'), ('Payment-completed', 'Payment Completed')], default='Placed', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('updated', 'Updated'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Partially-paid', 'Partially Paid'), ('Payment-pending', 'Payment Pending'), ('Payment-completed', 'Payment Completed')], default='Placed', max_length=32),
        ),
    ]
