# Generated by Django 5.0.3 on 2024-05-31 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_billingaddress_onlinepayment'),
        ('users', '0014_alter_address_address_type_companybillingaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.company'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='payment_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='payment_type',
            field=models.CharField(choices=[('online', 'Online'), ('cash', 'Cash')], default='cash', max_length=16),
        ),
    ]
