# Generated by Django 5.0.3 on 2024-06-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_orderpayment_company_orderpayment_payment_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellcart',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
    ]
