# Generated by Django 5.0.3 on 2024-06-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sellcart_is_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellcart',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('updated', 'Updated'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Partially-paid', 'Partially Paid'), ('Payment-pending', 'Payment Pending'), ('Payment-completed', 'Payment Completed'), ('Delivered', 'Delivered')], default='Placed', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('updated', 'Updated'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Partially-paid', 'Partially Paid'), ('Payment-pending', 'Payment Pending'), ('Payment-completed', 'Payment Completed'), ('Delivered', 'Delivered')], default='Placed', max_length=32),
        ),
    ]
