# Generated by Django 5.0.3 on 2024-06-22 11:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_orderpayment_status_delete_onlinepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('session_data', models.JSONField(blank=True, default=dict, null=True)),
                ('order_payment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.orderpayment')),
            ],
            options={
                'db_table': 'lunsjavtale_online_payments',
            },
        ),
    ]
