# Generated by Django 5.0.3 on 2024-07-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_onlinepayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinepayment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='order',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productrating',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellcart',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellcart',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Updated', 'Updated'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Partially-paid', 'Partially Paid'), ('Payment-pending', 'Payment Pending'), ('Payment-completed', 'Payment Completed'), ('Processing', 'Processing'), ('Ready-to-deliver', 'Ready To Deliver'), ('Delivered', 'Delivered')], default='Placed', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Updated', 'Updated'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Partially-paid', 'Partially Paid'), ('Payment-pending', 'Payment Pending'), ('Payment-completed', 'Payment Completed'), ('Processing', 'Processing'), ('Ready-to-deliver', 'Ready To Deliver'), ('Delivered', 'Delivered')], default='Placed', max_length=32),
        ),
    ]
