# Generated by Django 5.0.3 on 2024-09-14 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_orderstatus_note'),
        ('scm', '0016_product_note_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='deduction',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='altercart',
            name='base',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alter_cart', to='sales.usercart'),
        ),
        migrations.AlterField(
            model_name='sellcart',
            name='ingredients',
            field=models.ManyToManyField(blank=True, help_text='Allergies', to='scm.ingredient'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='ingredients',
            field=models.ManyToManyField(blank=True, help_text='Allergies', to='scm.ingredient'),
        ),
    ]
