# Generated by Django 4.2.28 on 2026-05-09 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_orderpayment_deduction_alter_altercart_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='attention_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productrating',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_ratings', to='sales.order'),
        ),
        migrations.AddField(
            model_name='productrating',
            name='replied_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productrating',
            name='reply_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productrating',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
