# Generated by Django 4.2.28 on 2026-05-13 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0019_product_menu_type'),
        ('users', '0023_alter_resetpassword_token'),
        ('sales', '0014_productrating_attention_required_productrating_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('customer_type', models.CharField(choices=[('Corporate', 'Corporate'), ('Private', 'Private')], default='Private', max_length=32)),
                ('company_name', models.CharField(blank=True, max_length=256, null=True)),
                ('organization_number', models.CharField(blank=True, max_length=64, null=True)),
                ('invoice_reference', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('delivery_address_str', models.TextField()),
                ('invoice_address_str', models.TextField()),
                ('invoice_suite', models.CharField(blank=True, max_length=128, null=True)),
                ('invoice_postal_code', models.CharField(blank=True, max_length=16, null=True)),
                ('invoice_city', models.CharField(blank=True, max_length=128, null=True)),
                ('event_name', models.CharField(blank=True, max_length=256, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('person_count', models.PositiveIntegerField(default=1)),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Placed', 'Placed'), ('Updated', 'Updated'), ('Partially-paid', 'Partially Paid'), ('Payment-pending', 'Payment Pending'), ('Payment-completed', 'Payment Completed'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Processing', 'Processing'), ('Ready-to-deliver', 'Ready To Deliver'), ('Delivered', 'Delivered')], default='Placed', max_length=32)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_orders', to='users.vendor')),
            ],
            options={
                'db_table': 'lunsjavtale_client_orders',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ClientOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=256)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.clientorder')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scm.product')),
            ],
            options={
                'db_table': 'lunsjavtale_client_order_items',
            },
        ),
    ]
