# Generated by Django 4.2.28 on 2026-05-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_clientorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
