# Generated by Django 4.2.28 on 2026-05-19 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_vendor_is_featured'),
        ('sales', '0017_clientorder_due_date_order_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_order', to='sales.order'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Updated', 'Updated'), ('Partially-paid', 'Partially Paid'), ('Payment-pending', 'Payment Pending'), ('Payment-completed', 'Payment Completed'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Processing', 'Processing'), ('Ready-to-deliver', 'Ready To Deliver'), ('Delivered', 'Delivered'), ('Draft', 'Draft')], default='Placed', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='users.company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Updated', 'Updated'), ('Partially-paid', 'Partially Paid'), ('Payment-pending', 'Payment Pending'), ('Payment-completed', 'Payment Completed'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Processing', 'Processing'), ('Ready-to-deliver', 'Ready To Deliver'), ('Delivered', 'Delivered'), ('Draft', 'Draft')], default='Placed', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Updated', 'Updated'), ('Partially-paid', 'Partially Paid'), ('Payment-pending', 'Payment Pending'), ('Payment-completed', 'Payment Completed'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Processing', 'Processing'), ('Ready-to-deliver', 'Ready To Deliver'), ('Delivered', 'Delivered'), ('Draft', 'Draft')], default='Placed', max_length=32),
        ),
    ]
