# Generated by Django 5.0.3 on 2024-03-31 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'FAQ Categories',
                'db_table': 'lunsjavtale_faq_categories',
            },
        ),
        migrations.CreateModel(
            name='FollowUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('link_type', models.CharField(blank=True, max_length=32, null=True)),
                ('link', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Follow Us',
                'db_table': 'lunsjavtale_follow_us',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'lunsjavtale_languages',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lunsjavtale_partners',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SupportedBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lunsjavtale_supported_brands',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TypeOfAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Address Type',
                'verbose_name_plural': 'Address Types',
                'db_table': 'lunsjavtale_address_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ValidArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('post_code', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'lunsjavtale_valid_areas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WhoUAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, max_length=32, null=True)),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=32, null=True)),
                ('additional_info', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name_plural': 'Who U Are',
                'db_table': 'lunsjavtale_who_u_are',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='faqs', to='core.faqcategory')),
            ],
            options={
                'db_table': 'lunsjavtale_faqs',
            },
        ),
        migrations.CreateModel(
            name='WhoUAreAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.TextField()),
                ('is_cover', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('who_u_are', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.whouare')),
            ],
            options={
                'db_table': 'lunsjavtale_who_u_are_attachments',
                'ordering': ['-id'],
            },
        ),
    ]
