# Generated by Django 5.0.3 on 2024-04-06 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=32, null=True)),
                ('contact', models.CharField(blank=True, max_length=32, null=True)),
                ('number_of_employees', models.PositiveIntegerField(default=1)),
                ('post_code', models.PositiveIntegerField(default=1)),
                ('message', models.CharField(blank=True, max_length=32, null=True)),
                ('agree_to_privacy_policy', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
                'db_table': 'lunsjavtale_contact_us',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='followus',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validarea',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='faqs', to='core.faqcategory'),
        ),
        migrations.AlterField(
            model_name='followus',
            name='link_type',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='followus',
            name='title',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='whouare',
            name='role',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='whouare',
            name='title',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
