# Generated by Django 5.0.3 on 2024-04-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactus_followus_image_url_validarea_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=32, null=True)),
                ('description', models.TextField()),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Promotion',
                'db_table': 'lunsjavtale_promotion',
                'ordering': ['-id'],
            },
        ),
        migrations.RenameField(
            model_name='followus',
            old_name='image_url',
            new_name='photo_url',
        ),
    ]
