# Generated by Django 5.0.3 on 2024-04-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_promotion_rename_image_url_followus_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
