# Generated by Django 5.0.3 on 2024-05-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_promotion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_visible_on_home_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='followus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='site_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='product_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportedbrand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supportedbrand',
            name='site_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whouare',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
