# Generated by Django 5.0.3 on 2024-04-18 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactus_followus_image_url_validarea_is_active_and_more'),
        ('scm', '0003_remove_product_photo_url_and_more'),
        ('users', '0003_company_is_contacted_company_is_deleted_company_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpromocode',
            name='promo_code',
        ),
        migrations.RemoveField(
            model_name='userpromocode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_phone',
        ),
        migrations.AddField(
            model_name='address',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='scm.ingredient'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.ManyToManyField(blank=True, to='core.language'),
        ),
        migrations.AlterField(
            model_name='company',
            name='working_email',
            field=models.EmailField(max_length=256, unique=True),
        ),
        migrations.RenameModel(
            old_name='PromoCode',
            new_name='Coupon',
        ),
        migrations.DeleteModel(
            name='UserPromoCode',
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('discounted_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_payment_success', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='used_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lunsjavtale_user_promo_codes',
            },
        ),
        migrations.DeleteModel(
            name='UserLanguage',
        ),
    ]
