# Generated by Django 5.0.3 on 2024-04-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_address_deleted_on_company_allowance_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='cover_photo_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='slogan',
        ),
        migrations.RemoveField(
            model_name='company',
            name='social_media_links',
        ),
        migrations.AddField(
            model_name='company',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='no_of_employees',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
