# Generated by Django 5.0.3 on 2024-04-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='added_for',
            field=models.ManyToManyField(blank=True, to='users.company'),
        ),
    ]
