# Generated by Django 5.0.3 on 2024-05-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_vendor_company_invoice_amount_company_ordered_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
