# Generated by Django 5.0.3 on 2024-05-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='cover_photo_file_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='logo_file_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='file_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='file_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='file_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
