# Generated by Django 5.0.3 on 2024-06-14 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_address_address_type_companybillingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('developer', 'Developer'), ('sub-admin', 'Sub Admin'), ('seo-manager', 'Seo Manager'), ('system-manager', 'System Manager'), ('user', 'User'), ('vendor', 'Vendor'), ('company-owner', 'Company Owner'), ('company-manager', 'Company Manager'), ('company-employee', 'Company Employee')], default='user', max_length=16),
        ),
        migrations.CreateModel(
            name='UserSocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('social_id', models.CharField(max_length=100)),
                ('social_type', models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'Linkedin'), ('google', 'Google'), ('apple', 'Apple')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lunsjavtale_user_social_accounts',
                'unique_together': {('user', 'social_type')},
            },
        ),
    ]
