# Generated by Django 5.0.3 on 2024-07-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_role_usersocialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
    ]
