# Generated by Django 4.2.28 on 2026-02-25 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_clientdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofhistory',
            name='header',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitofhistory',
            name='new_meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitofhistory',
            name='old_meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitofhistory',
            name='perform_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perform_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
