# Generated by Django 4.2.28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_followus_title'),
        ('users', '0017_alter_unitofhistory_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='service_areas',
            field=models.ManyToManyField(
                blank=True,
                help_text='Post codes/areas where this vendor provides service.',
                related_name='vendors_serving',
                to='core.validarea',
            ),
        ),
    ]
