# Generated by Django 4.2.28 on 2026-03-26

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_vendor_service_areas"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdetails",
            name="default_vendor_commission_percentage",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Default platform commission (%) taken from vendor sales when vendor-specific commission is not set.",
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="commission_percentage",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Platform commission (%) override for this vendor. If empty, the global default is used.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]

