# Generated by Django 4.2.28 on 2026-05-09 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_clientdetails_default_vendor_commission_percentage_and_vendor_commission_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('delivery_mode', models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup'), ('both', 'Delivery and pickup')], default='both', max_length=16)),
                ('delivery_available', models.BooleanField(default=True)),
                ('pickup_available', models.BooleanField(default=True)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('pickup_instructions', models.TextField(blank=True, null=True)),
                ('base_delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_delivery_over', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('same_fee_all_distances', models.BooleanField(default=True)),
                ('delivery_days', models.JSONField(blank=True, default=list)),
                ('delivery_time_slots', models.JSONField(blank=True, default=list)),
                ('max_deliveries_per_day', models.PositiveIntegerField(default=0)),
                ('max_orders_per_time_slot', models.PositiveIntegerField(default=0)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_settings', to='users.vendor')),
            ],
            options={
                'verbose_name_plural': 'Vendor delivery settings',
                'db_table': 'lunsjavtale_vendor_delivery_settings',
            },
        ),
    ]
