# Generated by Django 4.2.28 on 2026-05-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_vendordeliverysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_kitchen_active',
            field=models.BooleanField(default=True),
        ),
    ]
