# Generated by Django 4.2.28 on 2026-05-09 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_vendor_is_kitchen_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('organization_number', models.CharField(blank=True, max_length=64, null=True)),
                ('business_type', models.CharField(blank=True, max_length=64, null=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('business_hours', models.JSONField(blank=True, default=list)),
                ('notification_preferences', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(default='en', max_length=32)),
                ('region_currency', models.CharField(default='NOK', max_length=32)),
                ('time_zone', models.CharField(default='UTC', max_length=64)),
                ('store_connected', models.BooleanField(default=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_settings', to='users.vendor')),
            ],
            options={
                'verbose_name_plural': 'Vendor settings',
                'db_table': 'lunsjavtale_vendor_settings',
            },
        ),
    ]
