# Generated by Django 4.2.28 on 2026-05-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_vendorsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
