# Generated by Django 4.2.28 on 2026-05-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_resetpassword_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='industry_usage',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('developer', 'Developer'), ('sub-admin', 'Sub Admin'), ('seo-manager', 'Seo Manager'), ('system-manager', 'System Manager'), ('user', 'User'), ('client', 'Client'), ('vendor', 'Vendor'), ('company-owner', 'Company Owner'), ('company-manager', 'Company Manager'), ('company-employee', 'Company Employee')], default='user', max_length=16),
        ),
    ]
