# Generated by Django 4.2.28 on 2026-05-13 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_rename_country_address_receiving_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rewards_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('earn', 'Earned'), ('spend', 'Spent')], max_length=16)),
                ('source', models.CharField(choices=[('order', 'Order Placement'), ('review', 'Write Review'), ('referral', 'Invite Friends')], max_length=32)),
                ('points', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lunsjavtale_reward_transactions',
                'ordering': ['-created_on'],
            },
        ),
    ]
