# Generated by Django 4.2.28 on 2026-05-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_user_reward_points_user_rewards_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('developer', 'Developer'), ('sub-admin', 'Sub Admin'), ('seo-manager', 'Seo Manager'), ('system-manager', 'System Manager'), ('user', 'User'), ('vendor', 'Vendor'), ('company-owner', 'Company Owner'), ('company-manager', 'Company Manager'), ('company-employee', 'Company Employee')], default='user', max_length=16),
        ),
    ]
