# Generated by Django 4.2.28 on 2026-05-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_vendor_is_popular_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='vendordeliverysettings',
            name='max_delivery_time',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AddField(
            model_name='vendordeliverysettings',
            name='min_delivery_time',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
