# Generated by Django 4.2.28 on 2026-05-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_vendor_discount_percentage_vendor_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
