# Generated by Django 4.2.28 on 2026-06-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_vendor_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_photo_file_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='cover_photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
