# Generated by Django 5.0.3 on 2024-04-28 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0005_category_is_active_ingredient_is_active'),
        ('users', '0008_alter_user_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.CreateModel(
            name='FoodMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('meeting_type', models.CharField(choices=[('in-person', 'In Person'), ('interview', 'Interview'), ('remote', 'Remote'), ('others', 'Others')], default='in-person', max_length=32)),
                ('meeting_time', models.DateTimeField()),
                ('company_name', models.CharField(blank=True, max_length=128, null=True)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('attendees', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='users.company')),
                ('topics', models.ManyToManyField(blank=True, to='scm.category')),
            ],
            options={
                'db_table': 'lunsjavtale_food_meetings',
                'ordering': ['-id'],
            },
        ),
    ]
