# Generated by Django 5.0.3 on 2024-05-03 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0006_remove_product_discount_percent_remove_product_price_and_more'),
        ('users', '0009_vendor_company_invoice_amount_company_ordered_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='users.vendor'),
        ),
    ]
