# Generated by Django 5.0.3 on 2024-05-10 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0008_alter_product_name_alter_product_tax_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='file_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productattachment',
            name='file_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_with_tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='price adding TAX', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Final price'),
        ),
    ]
