# Generated by Django 5.0.3 on 2024-05-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0009_category_file_id_productattachment_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmeeting',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
