# Generated by Django 5.0.3 on 2024-06-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0010_foodmeeting_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmeeting',
            name='is_contacted',
        ),
        migrations.AddField(
            model_name='foodmeeting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('attended', 'Attended'), ('postponed', 'Postponed')], default='pending', max_length=32),
        ),
    ]
