# Generated by Django 5.0.3 on 2024-07-12 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0011_remove_foodmeeting_is_contacted_foodmeeting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_with_tax',
            field=models.DecimalField(decimal_places=2, help_text='price adding TAX', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Final price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
