# Generated by Django 5.0.3 on 2024-07-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0014_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
