# Generated by Django 5.0.3 on 2024-09-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0016_product_note_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('days', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'lunsjavtale_weekly_variant',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='weekly_variants',
            field=models.ManyToManyField(blank=True, related_name='products', to='scm.weeklyvariant'),
        ),
    ]
