# Generated by Django 4.2.28 on 2026-05-09 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0017_weeklyvariant_product_weekly_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='blackout_dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_dietary',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dietary_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='menu_status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('paused', 'Paused')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='min_lead_time_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='optional_add_ons',
            field=models.ManyToManyField(blank=True, related_name='included_in_menus', to='scm.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_type',
            field=models.CharField(choices=[('per-person', 'Per Person'), ('fixed-package', 'Fixed Package'), ('tray-based', 'Tray Based')], default='per-person', max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('menu', 'Menu'), ('add-on', 'Add On')], default='menu', max_length=16),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=128)),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('file_id', models.TextField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='scm.product')),
            ],
            options={
                'db_table': 'lunsjavtale_menu_items',
                'ordering': ['order', '-created_on'],
            },
        ),
    ]
