# Generated by Django 4.2.28 on 2026-05-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0018_product_available_days_product_blackout_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='menu_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
