# Generated by Django 5.0.3 on 2024-04-21 18:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'lunsjavtale_notification_templates',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('audience_type', models.CharField(choices=[('users', 'Users'), ('inactive-users', 'Inactive Users'), ('admins', 'Admins'), ('custom', 'Custom'), ('company-owners', 'Company Owners'), ('company-managers', 'Company Managers'), ('company-staffs', 'Company Staffs')], max_length=32)),
                ('notification_type', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('scheduled_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_on', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='notified_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lunsjavtale_notifications',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='NotificationViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications_viewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lunsjavtale_notification_viewers',
                'ordering': ['-id'],
            },
        ),
    ]
